[package]
name = "b2sum"
version = "0.1.0"
authors = ["0xSilene"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
filebuffer = "0.4.0"
blake2-rfc = "0.2.18"
hex = "0.4.0"